### ISSUE TITLE
Librem Key branding

### ISSUE THREAD

**Issue by kylerankin** [Nitrokey/nitrokey-hotp-verification#2]
So as you know, we are branding our security token devices as "Librem Key" and I'd like to apply the same branding to the names and output of this userspace tool if possible as alternate commands, so for instance "libremkey-hotp-verification" would reference a "Librem Key" in its output while nitrokey-hotp-verification would reference "Nitrokey Pro" when it is run.

It doesn't seem like that many changes, and I'm happy to do them myself and push up a PR, but I wanted to check with you first to see if you had a preferred way that I tackle that.

**Comment by szszszsz** [comment]
Hi!
Sure. It looks like basing on the called name is the easiest way to do so. PR would be great!
