### ISSUE TITLE
v1.5: hotp-verification's reported  firmware version is incorrect

### ISSUE THREAD

**Issue by tlaurion** [Nitrokey/nitrokey-hotp-verification#33]
>The firmware version is also obviously incorrect, I suppose some meta-data-struct is not parsed correctly

_Originally posted by @daringer in https://github.com/Nitrokey/nitrokey-hotp-verification/issues/30#issuecomment-2060698008_

**Comment by sosthene-nitrokey** [comment]
The firmware version displayed is correctly that reported by the secrets app in the firmware. This version is not really relevant, and maybe should be changed, but this repo does not fail to handle it.

See https://github.com/Nitrokey/trussed-secrets-app/issues/113 for more info.
