### ISSUE TITLE
Make Info Output more verbose for nk3

### ISSUE THREAD

**Issue by nestire** [Nitrokey/nitrokey-hotp-verification#38]
See also issue #36 
Change this:
```

HOTP code verification application, version 1.6
Connected device status:
	Card serial: 0x7BE66C6C
	Firmware: v4.13
	Card counters: Admin 6, User 6
Operation success
```
To
```
HOTP code verification application, version 1.6
Connected device status:
	Card serial: 0x7BE66C6C
        Firmware Nitrokey 3: v1.7.1
	Firmware Secrets app: v4.13
	Secret app pin counters : Admin 6, User 6
Operation success
```

**Comment by daringer** [comment]
> Are they the same?

yes, secrets app only has a single pin.

Furthermore, this is the output for `info` does this mean the output should be different for pro/storage and nk3 (depending on what is connected)?

**Comment by tlaurion** [comment]
> Furthermore, this is the output for `info`. Does this mean the output should be different for pro/storage and nk3 (depending on what is connected)? 
> 

@daringer @JonathonHall-Purism : I see no reason why firmware version should not be sensical to the end user, ie: making it easy to search and know if it's the latest version and if he needs to upgrade.
