### ISSUE TITLE
hotp-verification 1.7+non-versioned bump commit (suppression of touch status) still wrong and still repeats itself

### ISSUE THREAD

**Issue by tlaurion** [Nitrokey/nitrokey-hotp-verification#52]
![signal-2024-12-16-13-53-14-019.jpg](https://github.com/user-attachments/assets/2c94539c-8d85-48ce-a03a-a68f37fa4568)

Ping @sosthene-nitrokey.

@jans23 
Heads PR from Nitrokey will be expected for anything heads related in the future, that's the last batch of tests I will do on my side without payment agreement.

Testing under https://github.com/linuxboot/heads/pull/1875, modules/hotp-verification and everything Nitrokey firmware, toolstack related = nitrokey responsibility to produce code, tests and results.

I will review those PR inside of Heads, but do not expect me to do anything more than that from now without a contractual payment agreement/compensation/time bank with Nitrokey signing a contract with myself that is legally bounding. Mutualism is expected. This is not even commensalism.

--- 

40h of my time for this feature freeze where payment still refused: we will inverse the roles and issues will be raised from my side under nitrokey repos, but testing of PR opened by nitrokey under Heads will be reviewed, challenged and when satisfying, merged. Maybe nitrokey will then and only then value the time involved into needed collaboration when he says how much involvement is required when it's not solely inside of their repo, but as of now they don't. 

We will inverse the roles in absence of a co-beneficial agreement and recognition of time spent to arrive to usable code. 

**This work on my side is not paid by profit sharing agreement, nor part of Heads community paid maintainership.**

This 40h should have been/should be paid by Nitrokey only, or made by Nitrokey, not by me where those 40h are totally dismissed as of now, still, to reverse regressions CAUSED by nitrokey changes with their nk3. Not my fault nor responsibility.

**Comment by daringer** [comment]
This is not a description of an error - I just read a lot of non technical text. Please re-open an issue, which describes your issue and how you would like to solve this and keep away the non-technical blabla...

**Comment by sosthene-nitrokey** [comment]
It still asks for the touch twice, because the reset and the setting of the PIN are separate operations.

I'm fixing the missing line break  in #53

**Comment by tlaurion** [comment]
> ![signal-2024-12-16-13-53-14-019.jpg](https://github.com/user-attachments/assets/2c94539c-8d85-48ce-a03a-a68f37fa4568)
> 

@sosthene-nitrokey lack of testing with real life dongles under Heads?

Sometimes it's one touch request. Sometimes it's 2. Sometimes it's 3.

As per image @daringer.

**Comment by sosthene-nitrokey** [comment]
If you see unexpected behaviour you think is a bug, please include the information on:

- How to reproduce it
- Expected output
- Observed output

**Comment by tlaurion** [comment]
> If you see unexpected behaviour you think is a bug, please include the information on:
> 
> - How to reproduce it
> - Expected output
> - Observed output

Regressions to nk2 is not mine to document nor flag. Please use Heads and make it par.
